const data = {
  id: '',
  breeder_id: '',
  name: '',
  type: '',
  breed: '',
  birth_date: '',
  quantity: '',
  age: '',
  fcr: '',
  bft: '',
  lsba: '',
  house_type: '',
  min_price: '',
  max_price: '',
  left_teats: '',
  right_teats: '',
  other_details: '',
  user_id: '',
  breeder: '',
  farm_name: '',
  farm_from_id: '',
  img_path: '',
};

export default data;