export { default as BreederProfile } from './BreederProfile';
export { default as Cart } from './Cart';
export { default as Dashboard } from './Dashboard';
export { default as Login } from './Login';
// export { default as FarmDetails } from './FarmDetails';
export { default as Inbox } from './Inbox';
export { default as Orders } from './Orders';
// export { default as ProductDetails } from './ProductDetails';
export { default as Products } from './Products';
export { default as Requests } from './Requests';
export { default as Settings } from './Settings';
export { default as Modal } from './Modal';